services:
  android-build:
    build:
      context: ..
      dockerfile: docker/Dockerfile.android
    volumes:
      - /home/codetown/Android/Sdk:/sdk
      - ..:/app
      - ../output:/output
      - /app/node_modules
    environment:
      - ANDROID_HOME=/sdk
